default:
  image: ubuntu:14.04
  before_script:
    - apt-get update && apt-get install -y python2.7 python-pip tar bash bash-doc bash-completion wget zip
  
job:
  script:
    - mkdir /protoc
    - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.12.2/protoc-3.12.2-linux-x86_64.zip -P /protoc
    - unzip /protoc/protoc-3.12.2-linux-x86_64.zip -d /protoc
    - export PATH=/protoc/bin:$PATH
    - chmod +x ./compile.py
    - ./compile.py cpp --generate_desc --include_imports --include_source_info
